[package]
name = "archeologit"
version = "0.5.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.15"
cli-table = "0.4"
clap = {version = "4.0.32", features = ["derive"]}
