name: Main

on:
  push:

env:
  CARGO_TERM_COLOR: always
  PACKAGE_NAME: archeologit

jobs:

  build-test:
    name: Build and test (${{ matrix.os }})

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: swatinem/rust-cache@v2
      - name: Build
        run: |
          cargo build --release
          ls -lah
      - name: "Upload archeologit"
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: target/debug/archeologit

  release-please:
    name: Execute release chores

    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    needs: build-test

    outputs:
      created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: artifacts
      - name: show ls
        run: |
          ls -lah
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          package-name: ${{ env.PACKAGE_NAME }}
          release-type: rust
          extra-files: |
            artifacts/*
